### ISSUE TITLE
Expand keywords option fails on filenames that have whitespace

### ISSUE THREAD

**Issue by EricBackus** [Oblomov/rcs-fast-export#5]
Hi,

I've been trying to use your excellent tool to migrate some RCS files into git. Mostly it works very well - thanks for making this available!

For my usage, I always want the expand keywords option turned on. In fact, I'm surprised that this isn't on by default, since that's what RCS does by default. But that's a separate issue.

The issue that I ran into is that expand keywords fails if the filename has whitespace in it. I found what seems to be a 2-character fix for this, which simply quotes the RCS filename with single quotes when calling co:

*** rcs-fast-export.rb  Thu Mar 30 15:57:21 2017
--- rcs-fast-export2.rb Thu Mar 30 19:35:06 2017
***************
*** 379,385 ****
        # TODO: what if a revision does not end with newline?
        # TODO this should be done internally, not piping out to RCS
        def RCS.expand_keywords(rcsfile, revision)
!               ret = ::File.read("|co -q -p#{revision} #{rcsfile}")
                lines = []
                ret.each_line do |line|
                        lines << line
--- 379,385 ----
        # TODO: what if a revision does not end with newline?
        # TODO this should be done internally, not piping out to RCS
        def RCS.expand_keywords(rcsfile, revision)
!               ret = ::File.read("|co -q -p#{revision} '#{rcsfile}'")
                lines = []
                ret.each_line do |line|
                        lines << line

I don't know ruby, but this worked for me and it seems like this should be a pretty safe fix. Would you consider adding it to rcs-fast-export?

**Comment by Oblomov** [comment]
Hello. I'm glad you found this program useful.

Concerning the choice to not expand keywords by default, this is done to reflect the actual changes being done in the commit: the whole point of RCS keywords is to NOT store their changes in the file itself, and we respect this when converting the repository to git. This is unlikely to change.

Concerning your issue, quoting the string is indeed the correct solution. However, the choice of single quotes will fail if the filename itself contains (an odd number of) single quotes. I've pushed a slightly different change that uses a function specifically designed for shell escaping. This should solve the problem. Feel free to try it and reopen the issue if the latest commit doesn't fix it for you.

**Comment by EricBackus** [comment]
Thanks, your change works for me, and of course it's better than just adding single quotes.
